spring:
  datasource:
    username: root
    password: wlqkcho515253~
    url: jdbc:mysql://localhost:3306/health
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true

  jpa:
    show-sql: true
    open-in-view: false
    database: mysql
    hibernate:
      naming:
        physical-strategy: com.doubleBulkUp.config.StrictCamelCasePhysicalNamingStrategy
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

sever:
  servlet:
    encoding:
      fore-response: true
logging:
  level:
    com.doubleBulkUp: debug
